// This file was autogenerated by closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../decresendo/decresendo.js', ['Decresendo'], ['Decresendo.MIDI', 'Decresendo.Score', 'Decresendo.Score.Loader']);
goog.addDependency('../../../decresendo/midi/midi.js', ['Decresendo.MIDI'], []);
goog.addDependency('../../../decresendo/score/score.js', ['Decresendo.Score'], []);
goog.addDependency('../../../decresendo/score/scoreloader.js', ['Decresendo.Score.Loader'], ['Decresendo', 'Decresendo.Score']);
goog.addDependency('../../../decresendo/score/scorenode.js', ['Decresendo.Score.Node'], ['Decresendo.Score']);
